- id: earthly-lint
  name: Lint earthly Earthfile
  description: This hook lints any Earthfiles in the project using earthly ls
  entry: hooks/earthly-lint
  language: script
  stages: [pre-commit, pre-merge-commit, manual]
  files: "Earthfile"
  pass_filenames: true
- id: earthly-target
  name: Run earthly target on Earthfile
  description: This hook runs an earthly target on a specific Earthfile whenever a file pattern changes
  entry: hooks/earthly-target
  language: script
  stages: [pre-commit, pre-merge-commit, manual]
  files: "Earthfile"
  pass_filenames: false
