#!/bin/bash -u
command -v "earthly" >/dev/null 2>&1 \
  || { echo >&2 "I require earthly but it's not installed.  Aborting."; exit 255; }
# Do some argument validation
if [ $# -lt 2 ]; then
  echo "args: $@"
  echo >&2 "ERROR: must pass atleast one valid Earthfile and one +target argument"; exit 255
fi
if [ ! -f "$1" ] || [ "$(basename "$1")" != "Earthfile" ]; then
  echo >&2 "ERROR: invalid Earthfile passed!"; exit 255;
fi
EARTHFILE="$1"; shift
TARGET=""
for arg in "$@"; do
  if [[ "$arg" == "+"* ]] && [[ "$arg" != "+" ]]; then
    TARGET="$arg"; continue
  fi
  if [[ "$arg" != "--"* ]]; then
    echo >&2 "ERROR: args only supports passing a target or argument prefixed with --"; exit 255
  fi
done
if [ -z "$TARGET" ]; then
  echo >&2 "ERROR: missing earthly target in args"; exit 255
fi
# Enter the directory where our Earthfile is located
cd "$(dirname "$EARTHFILE")"
# Run out target with any additional arguments
echo "$@"
exec earthly $@
